import { Router } from 'express';
import { adminRouter } from './admin.routes';
import { assistantRouter } from './assistant.routes';
import { authRouter } from './auth.routes';
import { bookingsRouter } from './bookings.routes';
import { complaintsRouter } from './complaints.routes';
import { filesRouter } from './files.routes';
import { partnerRouter } from './partner.routes';
import { catalogRouter } from './catalog.routes';
import { customerRouter } from './customer.routes';
import { geoRouter } from './geo.routes';
import { healthRouter } from './health.routes';
import { notificationRouter } from './notification.routes';
import { technicianRouter } from './technician.routes';
import { uploadRouter } from './upload.routes';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/', catalogRouter);
apiRouter.use('/uploads', uploadRouter);
apiRouter.use('/geo', geoRouter);
apiRouter.use('/assistant', assistantRouter);
apiRouter.use('/files', filesRouter);
apiRouter.use('/bookings', bookingsRouter);
apiRouter.use('/complaints', complaintsRouter);
apiRouter.use('/partner', partnerRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/customer', customerRouter);
apiRouter.use('/technician', technicianRouter);
apiRouter.use('/admin', adminRouter);
