import {
  AirVent,
  Armchair,
  BatteryCharging,
  Bath,
  BedDouble,
  Bike,
  Bug,
  BugOff,
  Cable,
  Camera,
  Car,
  CarFront,
  Cctv,
  CookingPot,
  Cylinder,
  DoorOpen,
  Droplets,
  Fan,
  Filter,
  Flame,
  GlassWater,
  Hammer,
  Heater,
  House,
  Laptop,
  Lightbulb,
  Microwave,
  MonitorCog,
  PaintRoller,
  Printer,
  Refrigerator,
  Scissors,
  ShowerHead,
  Smile,
  Snowflake,
  Sofa,
  Sparkles,
  SprayCan,
  Toilet,
  Tv,
  Umbrella,
  WashingMachine,
  Waves,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * A recognisable icon per service (fan for fan installation, bulb for lights…).
 * Services without an entry fall back to their category illustration.
 */
export const SERVICE_ICONS: Record<string, LucideIcon> = {
  // AC & Cooling
  'ac-general-service': AirVent,
  'ac-repair': Snowflake,
  'ac-installation': AirVent,
  'ac-gas-refill': Cylinder,
  'ac-uninstallation': Wrench,
  'air-cooler-repair': Wind,
  // Electrical
  'fan-installation': Fan,
  'electrical-repair': Zap,
  'light-installation': Lightbulb,
  'inverter-service': BatteryCharging,
  'house-wiring': Cable,
  // Plumbing
  'tap-repair': Droplets,
  'plumber-visit': Wrench,
  'water-tank-cleaning': Cylinder,
  'toilet-repair': Toilet,
  'drain-blockage': Waves,
  'motor-pump-repair': Droplets,
  // Carpentry
  'furniture-repair': Armchair,
  'door-repair': DoorOpen,
  'furniture-assembly': Hammer,
  'kitchen-cabinet-repair': Hammer,
  // Painting
  'room-painting': PaintRoller,
  'full-home-painting': House,
  waterproofing: Umbrella,
  // Appliance repair
  'washing-machine-repair': WashingMachine,
  'refrigerator-repair': Refrigerator,
  'tv-repair': Tv,
  'geyser-repair': Heater,
  'microwave-repair': Microwave,
  'chimney-cleaning': Flame,
  // Cleaning
  'home-deep-cleaning': Sparkles,
  'bathroom-cleaning': ShowerHead,
  'sofa-cleaning': Sofa,
  'kitchen-cleaning': CookingPot,
  // CCTV
  'cctv-installation': Cctv,
  'cctv-repair': Camera,
  // RO
  'ro-service': GlassWater,
  'ro-installation': GlassWater,
  'ro-filter-change': Filter,
  // Pest control
  'cockroach-control': Bug,
  'termite-control': BugOff,
  'mosquito-control': SprayCan,
  'bed-bug-control': BedDouble,
  // Computer & laptop
  'laptop-repair': Laptop,
  'desktop-printer-repair': Printer,
  'software-installation': MonitorCog,
  // Car & bike
  'car-wash': Car,
  'car-interior-cleaning': CarFront,
  'bike-service': Bike,
  // Salon at home
  'mens-haircut': Scissors,
  'facial-cleanup': Smile,
  waxing: Sparkles,
  // Bathroom fittings fall under plumbing searches too
  'bath-fittings': Bath,
};

/** Icon colour per category (matches the category illustrations). */
export const CATEGORY_ACCENT: Record<string, string> = {
  ac: 'text-sky-600',
  electrical: 'text-amber-500',
  plumbing: 'text-cyan-600',
  carpentry: 'text-orange-600',
  painting: 'text-indigo-600',
  appliance: 'text-blue-600',
  cleaning: 'text-amber-600',
  cctv: 'text-slate-700',
  ro: 'text-sky-600',
  pest: 'text-emerald-600',
  computer: 'text-indigo-600',
  vehicle: 'text-blue-600',
  salon: 'text-pink-600',
};
